export const listRes = {
  success: true,
  message: '操作成功！',
  code: 200,
  result: {
    B12A01: [
      {
        percentage: 0,
        name: 'A1',
        id: '1715922592965',
      },
      {
        percentage: 0,
        name: 'A2',
        id: '1715922592966',
      },
      {
        percentage: 0,
        name: 'A3',
        id: '1715922592967',
      },
      {
        percentage: 0,
        name: 'A4',
        id: '1715922592968',
      },
      {
        percentage: 0,
        name: 'A5',
        id: '1715922592969',
      },
      {
        percentage: 0,
        name: 'A6',
        id: '1715922592970',
      },
      {
        percentage: 0,
        name: 'A7',
        id: '1715922592971',
      },
      {
        percentage: 0,
        name: 'A8',
        id: '1715922592972',
      },
    ],
    B12A02: [
      {
        percentage: 0,
        name: 'A9',
        id: '1715922592973',
      },
      {
        percentage: 0,
        name: 'A10',
        id: '1715922592974',
      },
      {
        percentage: 0,
        name: 'A11',
        id: '1715922592975',
      },
      {
        percentage: 0,
        name: 'A12',
        id: '1715922592976',
      },
      {
        percentage: 0,
        name: 'A13',
        id: '1715922592978',
      },
      {
        percentage: 0,
        name: 'A14',
        id: '1715922592979',
      },
      {
        percentage: 0,
        name: 'A15',
        id: '1715922592980',
      },
      {
        percentage: 0,
        name: 'A16',
        id: '1715922592981',
      },
      {
        percentage: 0,
        name: 'A17',
        id: '1715922592982',
      },
      {
        percentage: 0,
        name: 'A18',
        id: '1715922592983',
      },
      {
        percentage: 0,
        name: 'A19',
        id: '1715922592984',
      },
      {
        percentage: 0,
        name: 'A20',
        id: '1715922592985',
      },
      {
        percentage: 0,
        name: 'A21',
        id: '1715922592986',
      },
      {
        percentage: 0,
        name: 'A22',
        id: '1715922592987',
      },
      {
        percentage: 0,
        name: 'A23',
        id: '1715922592988',
      },
      {
        percentage: 0,
        name: 'A24',
        id: '1715922592989',
      },
      {
        percentage: 0,
        name: 'A25',
        id: '1715922592991',
      },
      {
        percentage: 0,
        name: 'A26',
        id: '1715922592992',
      },
      {
        percentage: 0,
        name: 'A27',
        id: '1715922592993',
      },
      {
        percentage: 0,
        name: 'A28',
        id: '1715922592994',
      },
      {
        percentage: 0,
        name: 'A29',
        id: '1715922592995',
      },
      {
        percentage: 0,
        name: 'A30',
        id: '1715922592996',
      },
      {
        percentage: 0,
        name: 'A31',
        id: '1715922592997',
      },
      {
        percentage: 0,
        name: 'A32',
        id: '1715922592998',
      },
      {
        percentage: 0,
        name: 'A33',
        id: '1715922592999',
      },
      {
        percentage: 0,
        name: 'A34',
        id: '1715922593000',
      },
      {
        percentage: 0,
        name: 'A35',
        id: '1715922593001',
      },
      {
        percentage: 0,
        name: 'A36',
        id: '1715922593003',
      },
      {
        percentage: 0,
        name: 'A37',
        id: '1715922593004',
      },
      {
        percentage: 0,
        name: 'B1',
        id: '1715922593005',
      },
      {
        percentage: 0,
        name: 'B2',
        id: '1715922593006',
      },
      {
        percentage: 0,
        name: 'B3',
        id: '1715922593007',
      },
      {
        percentage: 0,
        name: 'B4',
        id: '1715922593008',
      },
      {
        percentage: 0,
        name: 'B5',
        id: '1715922593009',
      },
      {
        percentage: 0,
        name: 'B6',
        id: '1715922593010',
      },
      {
        percentage: 0,
        name: 'B7',
        id: '1715922593011',
      },
      {
        percentage: 0,
        name: 'B8',
        id: '1715922593012',
      },
      {
        percentage: 0,
        name: 'B9',
        id: '1715922593013',
      },
      {
        percentage: 0,
        name: 'B10',
        id: '1715922593015',
      },
      {
        percentage: 0,
        name: 'B11',
        id: '1715922593016',
      },
      {
        percentage: 0,
        name: 'B12',
        id: '1715922593017',
      },
      {
        percentage: 0,
        name: 'B13',
        id: '1715922593018',
      },
      {
        percentage: 0,
        name: 'B14',
        id: '1715922593019',
      },
      {
        percentage: 0,
        name: 'B15',
        id: '1715922593020',
      },
      {
        percentage: 0,
        name: 'B16',
        id: '1715922593021',
      },
      {
        percentage: 0,
        name: 'B17',
        id: '1715922593022',
      },
      {
        percentage: 0,
        name: 'B18',
        id: '1715922593023',
      },
    ],
  },
  timestamp: 1718790783020,
}

export const processList = {
  success: true,
  message: '操作成功！',
  code: 200,
  result: [
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794939975317512194',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '起重船进点、抛锚定位',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794940278574080002',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '稳桩平台吊放、支撑桩插打',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794940398480842753',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '钢管桩运输驳船就位',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794940586058506241',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '钢管桩主吊具、溜尾吊具挂设',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794940686419812353',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '钢管桩起吊、翻身至竖直状态',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794940812446064641',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '将钢管桩插入稳桩平台内',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794940986274799617',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '钢管桩自重下沉至稳定',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794941084769640449',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '主吊具拆除',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794941184870899713',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '起吊安装桩锤',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794941290366033921',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '钢管桩锤击到位、验收',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794941380614873089',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '安装内平台、桩顶法兰 UT检测、竣工测量',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794942796267970561',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '稳桩平台支撑桩拔除、起吊移位',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794943030876364801',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '附属结构套笼安装',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794943133527760897',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '重新起吊稳桩平台，船舶起锚移位',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794943431264624642',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '船舶就位',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794945801256099842',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '塔筒运输船靠泊',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794946090113622017',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '底节塔筒吊装、螺栓紧固',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794946495069478914',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '塔外爬梯吊装、螺栓紧固',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794947137594908674',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '第二节塔筒吊装、螺栓紧固',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794947330570641410',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '第三节塔筒吊装、螺栓紧固',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794947471604113410',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '第四节塔筒吊装、螺栓紧固',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794947667280977922',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '主机、叶片运输船靠泊',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794947896994619394',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '主机过驳至安装船甲板，进行起吊前推备工作',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794948219771478017',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '主机起吊安装、螺栓紧固',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794948313019244545',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '第一支叶片安装',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794948418761842690',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '第二支叶片安装',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794948522805747714',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '第三支叶片安装',
    },
    {
      id: null,
      createBy: null,
      createTime: null,
      updateBy: null,
      updateTime: null,
      delFlag: null,
      sysOrgCode: null,
      projectId: null,
      pbsId: null,
      processId: '1794948726816694273',
      createName: null,
      unitId: null,
      unitName: null,
      startTime: null,
      endTime: null,
      useTime: null,
      constructionState: null,
      content: null,
      file: null,
      processName: '力矩螺栓验收、终检',
    },
  ],
  timestamp: 1718792167896,
}
